### ISSUE TITLE
Won't extract the archive on Windows based runner  

### ISSUE THREAD

**Issue by nikolai-in** [kenji-miyake/setup-git-cliff#87]
I don't know how or why, but after some time it has stopped working on my self-hosted Gitea actions runner on win 11
![image](https://github.com/kenji-miyake/setup-git-cliff/assets/87097942/022c4ecf-4da8-459c-867f-70c56acb5c8b)
I suppose it might be Microsoft playing pranks on me with auto updates, but I am too lazy to check changelogs...
Anyway, just appending archive extension after UUID seems to do the trick: 
![image](https://github.com/kenji-miyake/setup-git-cliff/assets/87097942/5f1baa03-b1bf-4517-ba16-75bf46aab12b)
Some time later I might clean up my code and make a PR

**Comment by nikolai-in** [comment]
BTW I have no idea how `/tmp/git-cliff` works on Windows :-)

**Comment by kenji-miyake** [comment]
@nikolai-in Hi, thanks for reporting it. I added the Windows CI job but couldn't reproduce it. Could you try reproducing it on CI?
https://github.com/kenji-miyake/setup-git-cliff/pull/89
https://github.com/kenji-miyake/setup-git-cliff/actions/runs/9819856957/job/27113836441?pr=89

**Comment by nikolai-in** [comment]
I should have tried that before, after all my use case is unusual and it's probably caused by the difference in environments. Might be reasonable to only keep this fix in my fork. And I only managed to reproduce this on 2 out of 3 Windows 11 machines that I have.

**Comment by nikolai-in** [comment]
And for some reason I haven't thought of comparing the poweshell versions, will do that when I get home

**Comment by nikolai-in** [comment]
@kenji-miyake It turns out that PowerShell and its modules in Windows 11 are quite old
![image](https://github.com/kenji-miyake/setup-git-cliff/assets/87097942/4514495b-9358-463f-8ebe-6ada8973c9b5)
Might be reasonable to just close this issue now, however I am amazed that for some reason it has worked before on the same machine. Sorry for wasting your time.

**Comment by kenji-miyake** [comment]
@nikolai-in Got it. No need to feel sorry! Keeping any information may be helpful for others in the future. :relaxed: 
Thanks for your detailed report and contribution. :pray:
